# Generated by Django 2.1.1 on 2018-09-10 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightsinfo',
            old_name='title',
            new_name='name',
        ),
    ]
