# Generated by Django 2.1.1 on 2018-09-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20180912_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flights',
            options={'verbose_name_plural': 'flights'},
        ),
    ]
