# Generated by Django 2.1.1 on 2018-09-13 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20180913_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircraft',
            options={'verbose_name_plural': 'Aircraft'},
        ),
        migrations.RenameField(
            model_name='flights',
            old_name='content',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='aircraft_sel',
        ),
        migrations.AddField(
            model_name='aircraft',
            name='license_type',
            field=models.CharField(default='Aircraft', max_length=40),
        ),
        migrations.AddField(
            model_name='flights',
            name='actual_instr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='airports_visited',
            field=models.CharField(default='Airports', max_length=100),
        ),
        migrations.AddField(
            model_name='flights',
            name='cross_country',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='day',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='dual_rec',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='fly_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='flights',
            name='license_type',
            field=models.CharField(default='Aircraft', max_length=40),
        ),
        migrations.AddField(
            model_name='flights',
            name='man_type',
            field=models.CharField(default='Manufacturer', max_length=200),
        ),
        migrations.AddField(
            model_name='flights',
            name='night',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='no_instument_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flights',
            name='no_ldg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='pic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='sim_instr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flights',
            name='snippet',
            field=models.TextField(blank=True, default='snippet'),
        ),
        migrations.AddField(
            model_name='flights',
            name='tail_number',
            field=models.CharField(default='Tail Number', max_length=25),
        ),
    ]
