# Generated by Django 2.1.1 on 2018-09-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_aircraft_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='rand',
            field=models.CharField(default='a', max_length=1),
        ),
    ]
