# Generated by Django 2.1.1 on 2018-09-20 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_aircraft_rand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aircraft',
            old_name='rand',
            new_name='randz',
        ),
    ]
