# Generated by Django 2.1.1 on 2018-09-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0009_remove_aircraft_randz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(default='https://qph.fs.quoracdn.net/main-qimg-721f8fad881515f2e901f6a68151cd55-c', upload_to=''),
        ),
    ]
