# Generated by Django 2.1.1 on 2018-09-20 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0013_auto_20180920_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='man_type',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='pic_count',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='tail_number',
        ),
        migrations.AddField(
            model_name='flights',
            name='aircraft',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
    ]
