# Generated by Django 2.1.1 on 2018-09-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0014_auto_20180920_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(default='/plane.jpg', upload_to='aircrafts/%Y/%m/%D/'),
        ),
    ]
