# Generated by Django 2.1.1 on 2018-09-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0015_auto_20180920_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='actual_instr',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='airports_visited',
            field=models.CharField(blank=True, default='Airports', max_length=100),
        ),
        migrations.AlterField(
            model_name='flights',
            name='cross_country',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='day',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='dual_rec',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='night',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='no_instument_app',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='flights',
            name='no_ldg',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='pic',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='sim_instr',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
