# Generated by Django 2.1.1 on 2018-09-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0017_auto_20180921_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='night',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
