# Generated by Django 2.1.1 on 2018-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0019_auto_20180923_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='license_type',
            field=models.CharField(default='Airplane SEL', max_length=40),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='photo',
            field=models.ImageField(blank=True, default='/plane.jpg', upload_to='aircrafts/%Y/%m/%D/'),
        ),
    ]
