# Generated by Django 2.1.1 on 2018-09-25 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0022_auto_20180925_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='actual_instr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='aircraft',
            field=models.ForeignKey(default=uuid.uuid4, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.Aircraft'),
        ),
        migrations.AlterField(
            model_name='flights',
            name='cross_country',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='day',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='dual_rec',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='night',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='no_instument_app',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='no_ldg',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='pic',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='sim_instr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='total_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
