# Generated by Django 2.1.1 on 2018-09-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0022_billing'),
        ('flights', '0023_auto_20180925_2006'),
    ]

    operations = [
    ]
